version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.3.0
    ports:
      - "127.0.0.1:5001:5001"
    volumes:
      - "./uid2-mock-data/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "./uid2-mock-data/localstack/s3:/s3"
    environment:
      - EDGE_PORT=5001
