name: Build and Test
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-build-and-test.yaml@v3
    with:
      java_version: 21
    secrets: inherit

  javascript-tests:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run JavaScript tests
        run: |
          cd webroot/js/test
          node --test *.test.mjs
