name: Release Docker Image
run-name: ${{ inputs.release_type == 'Snapshot' && 'Publish pre-release' || format('Release {0}', inputs.release_type)}} Docker Image by @${{ github.actor }}  
on:
  pull_request:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'The type of release'
        options:
        - Major
        - Minor
        - Patch
        - Snapshot

jobs:
  Image:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/v2-shared-publish-docker-versioned.yaml@tjm-UID2-2325-new-shared-docker-image-pipeline
    with: 
      release_type: ${{ inputs.release_type }}
      cloud_provider: 'default'
    secrets: inherit
